In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(iris.data,columns = iris.feature_names)

In [5]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
df['flower'] = iris.target

In [7]:
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])

In [8]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        flower  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [11]:
from sklearn.svm import SVC

In [12]:
model1 = SVC(kernel='rbf',C=30,gamma='auto')

In [13]:
model1.fit(x_train,y_train)

SVC(C=30, gamma='auto')

In [14]:
model1.score(x_test,y_test)

0.9555555555555556

In [15]:
from sklearn.model_selection import cross_val_score

In [16]:
cross_val_score(SVC(C=10,kernel='linear',gamma='auto'), iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [17]:
cross_val_score(SVC(C=20,kernel='rbf',gamma='auto'), iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [18]:
cross_val_score(SVC(C=10,kernel='rbf',gamma='auto'), iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [19]:
import numpy as np

In [20]:
kernels=  ['rbf','linear']
c = [1,10,20,30]
avg_scores = {}
for kvals in kernels:
    for cvals in c:
        cv_score = cross_val_score(SVC(kernel=kvals,C=cvals,gamma='auto'), iris.data,iris.target,cv=5)
        avg_scores[kvals +'_'+ str(cvals)] = np.average(cv_score)
avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'rbf_30': 0.96,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'linear_30': 0.96}

In [21]:
# to do the upper block of code in one line we use gridsearchcv for parameter tunning
from sklearn.model_selection import GridSearchCV

In [22]:
clf = GridSearchCV(SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False )

In [23]:
clf.fit(iris.data,iris.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [24]:
clf.cv_results_

{'mean_fit_time': array([0.00392432, 0.00312362, 0.        , 0.        , 0.        ,
        0.        ]),
 'std_fit_time': array([0.00605201, 0.00624723, 0.        , 0.        , 0.        ,
        0.        ]),
 'mean_score_time': array([0.00039883, 0.        , 0.        , 0.00312428, 0.        ,
        0.        ]),
 'std_score_time': array([0.00079765, 0.        , 0.        , 0.00624857, 0.        ,
        0.        ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [25]:
df = pd.DataFrame(clf.cv_results_)

In [26]:
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.003924      0.006052         0.000399        0.000798       1   
1       0.003124      0.006247         0.000000        0.000000       1   
2       0.000000      0.000000         0.000000        0.000000      10   
3       0.000000      0.000000         0.003124        0.006249      10   
4       0.000000      0.000000         0.000000        0.000000      20   
5       0.000000      0.000000         0.000000        0.000000      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [27]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [28]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [29]:
clf.best_score_

0.9800000000000001

In [30]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [31]:
model_param = {
    'svm':{
        'model':SVC(gamma='auto'),
        'params':{
            'C': [1,10,20],
            'kernel':['rbf','linear']
        }
        
    },
    'random forest': {
        'model': RandomForestClassifier(),
        'params':{
            'n_estimators':[1,5,10]
        }   
    },
    'logistic regression': {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C':[1,5,10]
        }
    }
    
}

In [32]:
scores = []
for model_name,mp in model_param.items():
    clf = GridSearchCV(mp['model'],mp['params'],cv=5, return_train_score=False)
    clf.fit(iris.data,iris.target)
    scores.append({
        'model':model_name,
        'best_score':clf.best_score_,
        'best_param':clf.best_params_
    })

In [33]:
scores

[{'model': 'svm',
  'best_score': 0.9800000000000001,
  'best_param': {'C': 1, 'kernel': 'rbf'}},
 {'model': 'random forest',
  'best_score': 0.9600000000000002,
  'best_param': {'n_estimators': 1}},
 {'model': 'logistic regression',
  'best_score': 0.9666666666666668,
  'best_param': {'C': 5}}]

In [34]:
df = pd.DataFrame(scores,columns=['model','best_score','best_param'])

In [35]:
df

model  best_score                 best_param
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random forest    0.960000        {'n_estimators': 1}
2  logistic regression    0.966667                   {'C': 5}

# excersice 2

In [36]:
from sklearn import datasets
digits = datasets.load_digits()

In [37]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

In [38]:
model_param = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'param': {
            'C':[1,5,10],
            'kernel':['rbf','linear']
        }
    },
    'RandomForestclassifier':{
        'model': RandomForestClassifier(),
        'param': {
            'n_estimators':[1,5,10]
        }
    },
    'logisticregression': {
        'model': LogisticRegression(multi_class='auto',solver='liblinear'),
        'param': {
            'C':[1,5,10]
        }
    },
    'Gausian': {
        'model': GaussianNB(),
        'param':{}
    },
    'Multinomial': {
        'model': MultinomialNB(),
        'param':{}
    },
    'DecisionTreeClassifier': {
        'model': DecisionTreeClassifier(),
        'param': {
            'criterion': ["gini", "entropy"]
        }
    }
}

In [39]:
from sklearn.model_selection import GridSearchCV
import pandas as pd

In [40]:
scores=[]
for model_name, mp in model_param.items():
    clf = GridSearchCV(mp['model'], mp['param'],cv=5,return_train_score=False)
    clf.fit(digits.data,digits.target)
    scores.append({
        'model':model_name,
        'best_score':clf.best_score_,
        'best_param':clf.best_params_
    })

In [41]:
df = pd.DataFrame(scores)

In [42]:
df

model  best_score                    best_param
0                     svm    0.947697  {'C': 1, 'kernel': 'linear'}
1  RandomForestclassifier    0.905427          {'n_estimators': 10}
2      logisticregression    0.922114                      {'C': 1}
3                 Gausian    0.806928                            {}
4             Multinomial    0.870350                            {}
5  DecisionTreeClassifier    0.804703      {'criterion': 'entropy'}

In [43]:
from sklearn import datasets
digits = datasets.load_digits()

In [44]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

In [ ]:
model_param = {
    'RandomForest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [5,10,50,100,200]
        }
    },
    ''
}