In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('canada_per_capita_income.csv')

In [3]:
df

year  per capita income (US$)
0   1970              3399.299037
1   1971              3768.297935
2   1972              4251.175484
3   1973              4804.463248
4   1974              5576.514583
5   1975              5998.144346
6   1976              7062.131392
7   1977              7100.126170
8   1978              7247.967035
9   1979              7602.912681
10  1980              8355.968120
11  1981              9434.390652
12  1982              9619.438377
13  1983             10416.536590
14  1984             10790.328720
15  1985             11018.955850
16  1986             11482.891530
17  1987             12974.806620
18  1988             15080.283450
19  1989             16426.725480
20  1990             16838.673200
21  1991             17266.097690
22  1992             16412.083090
23  1993             15875.586730
24  1994             15755.820270
25  1995             16369.317250
26  1996             16699.826680
27  1997             17310.757750
28  1998             16622.671870
29  1999             17581.024140
30  2000             18987.382410
31  2001             18601.397240
32  2002             19232.175560
33  2003             22739.426280
34  2004             25719.147150
35  2005             29198.055690
36  2006             32738.262900
37  2007             36144.481220
38  2008             37446.486090
39  2009             32755.176820
40  2010             38420.522890
41  2011             42334.711210
42  2012             42665.255970
43  2013             42676.468370
44  2014             41039.893600
45  2015             35175.188980
46  2016             34229.193630

In [7]:
x = df[['year']]

In [8]:
y = df['per capita income (US$)']

In [25]:
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
from sklearn.model_selectionel_selection import train_test_split

In [11]:
x_train,x_test,y_train,_y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
lr = LinearRegression()

In [16]:
model = lr.fit(x_train,y_train)

In [23]:
model.coef_

array([820.31304136])

In [24]:
model.intercept_

-1616038.7782324494

In [17]:
model.predict(x_test)

array([22126.36537343, 31970.12186981, 21306.05233206, 35251.37403527,
       19665.42624933, 29509.18274571,  9821.66975295, 15563.86104251,
        3259.16542203, 20485.7392907 ,  6540.41758749,  2438.85238067,
        4899.79150476, 32790.43491117, 27048.24362162])

In [22]:
model.predict([[2020]])

array([40993.56532482])

In [21]:
model.score(x_test,_y_test)

0.9005705995581696

# 2nd excersice

In [28]:
data = pd.read_csv('hiring.csv')

In [29]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [52]:
x = data.iloc[:,0:3]

In [53]:
x

experience  test_score(out of 10)  interview_score(out of 10)
0        NaN                    8.0                           9
1        NaN                    8.0                           6
2       five                    6.0                           7
3        two                   10.0                          10
4      seven                    9.0                           6
5      three                    7.0                          10
6        ten                    NaN                           7
7     eleven                    7.0                           8

In [55]:
pip install word2number


  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5580 sha256=d7fd792c4482dbc4ba82a21754f4831c3329978a19d5cfa894dacddba6406604
  Stored in directory: c:\users\welcome\appdata\local\pip\cache\wheels\a0\4a\5b\d2f2df5c344ddbecb8bea759872c207ea91d93f57fb54e816e
Successfully built word2number


In [56]:
from word2number import w2n

In [60]:
data['experience'] = data['experience'].fillna('zero')

In [67]:
list1 = []
for exp in data['experience']:
    a = w2n.word_to_num(exp)
    list1.append(a)
list1

[0, 0, 5, 2, 7, 3, 10, 11]

In [70]:
data['experience'] = list1

In [71]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [72]:
from sklearn.impute import SimpleImputer

In [89]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(data[['test_score(out of 10)']])
data['test_score(out of 10)'] = imputer.transform(data[['test_score(out of 10)']])

In [90]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0               8.000000                           9      50000
1           0               8.000000                           6      45000
2           5               6.000000                           7      60000
3           2              10.000000                          10      65000
4           7               9.000000                           6      70000
5           3               7.000000                          10      62000
6          10               7.857143                           7      72000
7          11               7.000000                           8      80000

In [93]:
# can use astype('int') for converting it into integer
import math
ls =[]
for score in data['test_score(out of 10)']:
    a=math.floor(score)
    ls.append(a)


In [94]:
data['test_score(out of 10)'] =ls

In [95]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                      8                           9      50000
1           0                      8                           6      45000
2           5                      6                           7      60000
3           2                     10                          10      65000
4           7                      9                           6      70000
5           3                      7                          10      62000
6          10                      7                           7      72000
7          11                      7                           8      80000

In [96]:
x = data.iloc[:,0:3]

In [105]:
x

experience  test_score(out of 10)  interview_score(out of 10)
0           0                      8                           9
1           0                      8                           6
2           5                      6                           7
3           2                     10                          10
4           7                      9                           6
5           3                      7                          10
6          10                      7                           7
7          11                      7                           8

In [97]:
y = data['salary($)']

In [104]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [98]:
from sklearn.model_selection import train_test_split

In [109]:
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [110]:
from sklearn.linear_model import LinearRegression

In [111]:
lr = LinearRegression()

In [112]:
x_train.shape

(5, 3)

In [113]:
y_train

7    80000
2    60000
4    70000
3    65000
6    72000
Name: salary($), dtype: int64

In [114]:
model1 = lr.fit(x_train, y_train)

In [115]:
model1.predict([[2,9,6]])

array([56742.67782427])

In [116]:

model1.predict([[12,10,10]])

array([90510.46025105])

In [117]:
model1.score(x_test,y_test)

0.731401571963722

In [119]:
import joblib

In [120]:
joblib.dump(model1, 'model_joblib')

['model_joblib']

# exercise 3

In [122]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [123]:
df2 = pd.read_csv('car_exer.csv')

In [124]:
df2

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [130]:
car_model =pd.get_dummies(df2['Car Model'], drop_first=True)

In [135]:
df2 = pd.concat([df2,car_model], axis=1)

In [137]:
df2=df2.drop('Car Model', axis=1)

In [138]:
df2

Mileage  Sell Price($)  Age(yrs)  BMW X5  Mercedez Benz C class
0     69000          18000         6       1                      0
1     35000          34000         3       1                      0
2     57000          26100         5       1                      0
3     22500          40000         2       1                      0
4     46000          31500         4       1                      0
5     59000          29400         5       0                      0
6     52000          32000         5       0                      0
7     72000          19300         6       0                      0
8     91000          12000         8       0                      0
9     67000          22000         6       0                      1
10    83000          20000         7       0                      1
11    79000          21000         7       0                      1
12    59000          33000         5       0                      1

In [148]:
x = df2.drop('Sell Price($)',axis=1)

In [149]:
x

Mileage  Age(yrs)  BMW X5  Mercedez Benz C class
0     69000         6       1                      0
1     35000         3       1                      0
2     57000         5       1                      0
3     22500         2       1                      0
4     46000         4       1                      0
5     59000         5       0                      0
6     52000         5       0                      0
7     72000         6       0                      0
8     91000         8       0                      0
9     67000         6       0                      1
10    83000         7       0                      1
11    79000         7       0                      1
12    59000         5       0                      1

In [150]:
y = df2['Sell Price($)']

In [151]:
x_tr,x_te,y_tr,y_te = train_test_split(x,y,test_size=0.3,random_state=42)

In [152]:
from sklearn.linear_model import LinearRegression

In [153]:
lr3 = LinearRegression()

In [154]:
model3 = lr3.fit(x_tr,y_tr)


In [155]:
model3.predict([[45000,4,0,1]])

array([39105.7757338])

In [157]:
model3.score(x,y)

0.8890078151450576